# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shellforce}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chiharu Kawatake"]
  s.date = %q{2011-06-12}
  s.default_executable = %q{shellforce}
  s.description = %q{A simple wrapper of Salesforce REST API, inspired by the Rest Client developed by Adam Wiggins and Julien Kirch}
  s.email = %q{}
  s.executables = ["shellforce"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/shellforce",
    "lib/shellforce.rb",
    "lib/shellforce/agent.rb",
    "lib/shellforce/auth.rb",
    "lib/shellforce/client.rb",
    "lib/shellforce/config.rb",
    "lib/shellforce/config.ru",
    "lib/shellforce/forcedotcom.rb",
    "lib/shellforce/server.rb",
    "spec/shellforce_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mille-printemps/shellforce}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A simple wrapper of Salesforce REST API, inspired by the Rest Client developed by Adam Wiggins and Julien Kirch}
  s.test_files = ["spec/shellforce_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<omniauth>, ["= 0.2.0"])
      s.add_runtime_dependency(%q<multi_json>, ["= 0.0.5"])
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.6"])
      s.add_runtime_dependency(%q<rack>, [">= 1.2.3"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<omniauth>, ["= 0.2.0"])
      s.add_dependency(%q<multi_json>, ["= 0.0.5"])
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<json>, [">= 1.4.6"])
      s.add_dependency(%q<rack>, [">= 1.2.3"])
      s.add_dependency(%q<sinatra>, [">= 1.1.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<omniauth>, ["= 0.2.0"])
    s.add_dependency(%q<multi_json>, ["= 0.0.5"])
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<json>, [">= 1.4.6"])
    s.add_dependency(%q<rack>, [">= 1.2.3"])
    s.add_dependency(%q<sinatra>, [">= 1.1.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

